# Generated by Django 6.0.6 on 2026-06-26 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iso2_code', models.CharField(max_length=2, unique=True)),
                ('iso3_code', models.CharField(max_length=3, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('income_level', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_data.country')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_data.indicator')),
            ],
            options={
                'unique_together': {('country', 'indicator', 'year')},
            },
        ),
    ]
