# Generated by Django 6.0.6 on 2026-07-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['country', 'indicator', 'year']},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(default='MENA', max_length=100),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='core_data.country'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='core_data.indicator'),
        ),
    ]
