# Generated by Django 6.0.7 on 2026-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0002_alter_country_options_alter_datapoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='interpretation_direction',
            field=models.CharField(choices=[('higher_is_better', 'Higher is usually better'), ('lower_is_better', 'Lower is usually better'), ('context_dependent', 'Context dependent')], default='context_dependent', max_length=32),
        ),
    ]
