# Generated by Django 6.0.6 on 2026-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('countries', models.ManyToManyField(to='core_data.country')),
                ('indicators', models.ManyToManyField(to='core_data.indicator')),
            ],
        ),
    ]
